apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-test
  name: deploy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-test
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
